server:
    port: 80

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/springboot_vue
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 123456

## mybatis-plus相关配置
#mybatis-plus:
#    configuration:
#        #开启sql日志
#        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
